/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {
    let count = {};
    for (let i = 0; i < s.length; i++) {
        let char = s[i];
        if (char in count) {
            count[char] += 1;
        }
        else {
            count[char] = 1;
        }
    }
    for (let i = 0; i < t.length; i++) {
        let char = t[i];
        if (char in count && count[char] > 0) {
            count[char] -= 1;
        }
        else {
            return char;
        }
    }
};

console.log(findTheDifference("abcd", "abcde"));